"""ML-KEM-768 key encapsulation (FIPS 203)."""

from typing import ClassVar, final

from typing_extensions import Buffer, Self

__all__ = ["KeyPair", "PublicKey", "SecretKey"]

@final
class PublicKey:
    SIZE: ClassVar[int]
    CIPHERTEXT_SIZE: ClassVar[int]
    SHARED_SECRET_SIZE: ClassVar[int]
    def __new__(cls, key: Buffer) -> Self: ...
    @classmethod
    def from_bytes(cls, key: Buffer) -> Self: ...
    def encapsulate(self) -> tuple[bytes, bytes]: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class SecretKey:
    SIZE: ClassVar[int]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(cls, key: Buffer) -> Self: ...
    @classmethod
    def from_bytes(cls, key: Buffer) -> Self: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class KeyPair:
    SEED_SIZE: ClassVar[int]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    @classmethod
    def generate(cls) -> Self: ...
    @classmethod
    def from_seed(cls, seed: Buffer) -> Self: ...
    @classmethod
    def from_secret_key(cls, secret_key: SecretKey | Buffer) -> Self: ...
    @property
    def public_key(self) -> PublicKey: ...
    @property
    def secret_key(self) -> SecretKey: ...
    def decapsulate(self, ciphertext: Buffer) -> bytes: ...
    def __eq__(self, value: object, /) -> bool: ...
