from typing import ClassVar, final

from typing_extensions import Buffer, Self

from dryoc._types import EncryptedMessage as EncryptedMessage

__all__ = ["Box", "EncryptedMessage", "KeyPair", "PublicKey", "SealedBox", "SecretKey"]

@final
class PublicKey:
    """An X25519 public key."""

    SIZE: ClassVar[int]
    def __new__(cls, key: Buffer) -> Self: ...
    @classmethod
    def from_bytes(cls, key: Buffer) -> Self: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class SecretKey:
    """An X25519 secret key."""

    SIZE: ClassVar[int]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(cls, key: Buffer) -> Self: ...
    @classmethod
    def from_bytes(cls, key: Buffer) -> Self: ...
    @classmethod
    def generate(cls) -> Self: ...
    @property
    def public_key(self) -> PublicKey: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class KeyPair:
    """An X25519 key pair."""

    SEED_SIZE: ClassVar[int]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    @classmethod
    def generate(cls) -> Self: ...
    @classmethod
    def from_seed(cls, seed: Buffer) -> Self: ...
    @classmethod
    def from_secret_key(cls, secret_key: SecretKey | Buffer) -> Self: ...
    @property
    def public_key(self) -> PublicKey: ...
    @property
    def secret_key(self) -> SecretKey: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class Box:
    """Authenticated encryption between two parties (``crypto_box``)."""

    NONCE_SIZE: ClassVar[int]
    MAC_SIZE: ClassVar[int]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(cls, secret_key: KeyPair | SecretKey, public_key: PublicKey) -> Self: ...
    def encrypt(self, plaintext: Buffer, nonce: Buffer | None = None) -> EncryptedMessage: ...
    def decrypt(self, ciphertext: Buffer, nonce: Buffer) -> bytes: ...

@final
class SealedBox:
    """Anonymous public-key encryption (``crypto_box_seal``)."""

    OVERHEAD: ClassVar[int]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(cls, recipient: PublicKey | KeyPair | SecretKey) -> Self: ...
    @property
    def public_key(self) -> PublicKey: ...
    def encrypt(self, plaintext: Buffer) -> bytes: ...
    def decrypt(self, ciphertext: Buffer) -> bytes: ...
