from typing import ClassVar, Self, final

from typing_extensions import Buffer

__all__ = ["Ed25519ph", "SigningKey", "VerifyKey"]

@final
class VerifyKey:
    """An Ed25519 public key."""

    SIZE: ClassVar[int]
    def __new__(cls, key: Buffer) -> Self: ...
    @classmethod
    def from_bytes(cls, key: Buffer) -> Self: ...
    def verify(self, signature: Buffer, message: Buffer) -> None: ...
    def verify_combined(self, signed_message: Buffer) -> bytes: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class SigningKey:
    """An Ed25519 signing key."""

    SIZE: ClassVar[int]
    SEED_SIZE: ClassVar[int]
    SIGNATURE_SIZE: ClassVar[int]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(cls, secret_key: Buffer) -> Self: ...
    @classmethod
    def from_bytes(cls, secret_key: Buffer) -> Self: ...
    @classmethod
    def from_seed(cls, seed: Buffer) -> Self: ...
    @classmethod
    def generate(cls) -> Self: ...
    @property
    def verify_key(self) -> VerifyKey: ...
    def to_seed(self) -> bytes: ...
    def sign(self, message: Buffer) -> bytes: ...
    def sign_combined(self, message: Buffer) -> bytes: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class Ed25519ph:
    """Incremental Ed25519ph signing and verification."""

    def __new__(cls, data: Buffer | None = None) -> Self: ...
    def update(self, data: Buffer) -> None: ...
    def sign(self, signing_key: SigningKey) -> bytes: ...
    def verify(self, signature: Buffer, verify_key: VerifyKey) -> None: ...
