use zeroize::{Zeroize, ZeroizeOnDrop, Zeroizing};

use crate::blake2b;
use crate::error::Error;

// Version of the algorithm
pub(crate) const ARGON2_VERSION_NUMBER: u32 = 0x13;

// Memory block size in bytes
const ARGON2_BLOCK_SIZE: usize = 1024;
const ARGON2_QWORDS_IN_BLOCK: usize = ARGON2_BLOCK_SIZE / 8;

// Number of pseudo-random values generated by one call to Blake in Argon2i to
// generate reference block positions
const ARGON2_ADDRESSES_IN_BLOCK: u32 = 128;

// Pre-hashing digest length and its extension
const ARGON2_PREHASH_DIGEST_LENGTH: usize = 64;
const ARGON2_PREHASH_SEED_LENGTH: usize = 72;

const ARGON2_MIN_LANES: u32 = 1;
const ARGON2_MAX_LANES: u32 = 0xFFFFFF;

// Number of synchronization points between lanes per pass
const ARGON2_SYNC_POINTS: u32 = 4;

// Minimum and maximum digest size in bytes
const ARGON2_MIN_OUTLEN: usize = 16;
const ARGON2_MAX_OUTLEN: usize = 0xFFFFFFFF;

// Minimum and maximum number of memory blocks (each of BLOCK_SIZE bytes)
const ARGON2_MIN_MEMORY: u32 = 2 * ARGON2_SYNC_POINTS; // 2 blocks per slice

const fn min(a: u64, b: u64) -> u64 {
    [a, b][(a > b) as usize]
}

// Max memory size is half the addressing space, topping at 2^32 blocks (4
// TB)
const ARGON2_MAX_MEMORY_BITS: u32 =
    min(32, std::mem::size_of::<usize>() as u64 * 8 - 10 - 1) as u32;
const ARGON2_MAX_MEMORY: u32 = min(0xFFFFFFFF, 1u64 << ARGON2_MAX_MEMORY_BITS) as u32;

// Minimum and maximum number of passes
const ARGON2_MIN_TIME: u32 = 1;
const ARGON2_MAX_TIME: u32 = 0xFFFFFFFF;

// Minimum and maximum password length in bytes
const ARGON2_MIN_PWD_LENGTH: usize = 0;
const ARGON2_MAX_PWD_LENGTH: usize = 0xFFFFFFFF;

// Minimum and maximum associated data length in bytes
const ARGON2_MIN_AD_LENGTH: usize = 0;
const ARGON2_MAX_AD_LENGTH: usize = 0xFFFFFFFF;

// Minimum and maximum salt length in bytes
const ARGON2_MIN_SALT_LENGTH: usize = 8;
const ARGON2_MAX_SALT_LENGTH: usize = 0xFFFFFFFF;

// Minimum and maximum key length in bytes
const ARGON2_MIN_SECRET: usize = 0;
const ARGON2_MAX_SECRET: usize = 0xFFFFFFFF;

#[derive(Clone, Copy, PartialEq)]
pub(crate) enum Argon2Type {
    Argon2i  = 1,
    Argon2id = 2,
}

#[derive(Clone)]
#[repr(align(64))]
struct Block {
    v: [u64; ARGON2_QWORDS_IN_BLOCK],
}

impl Zeroize for Block {
    fn zeroize(&mut self) {
        // The derived implementation issues one volatile 8-byte store per
        // word. `zeroize_u64s` covers the same words with volatile stores of
        // the 16-byte aligned middle (`stp xzr, xzr` on AArch64) plus per-word
        // stores for any unaligned ends, which makes freeing the memory region
        // several times cheaper while every byte is still written by a
        // volatile store that the compiler cannot elide.
        crate::utils::zeroize_u64s(&mut self.v);
    }
}

impl Drop for Block {
    fn drop(&mut self) {
        self.zeroize();
    }
}

impl ZeroizeOnDrop for Block {}

#[cfg_attr(feature = "nightly", allow(clippy::derivable_impls))]
impl Default for Block {
    fn default() -> Self {
        Self {
            v: [0u64; ARGON2_QWORDS_IN_BLOCK],
        }
    }
}

macro_rules! apply_block_rounds {
    ($block:expr, $round:ident) => {{
        for i in 0..8 {
            $round(
                $block,
                16 * i,
                16 * i + 1,
                16 * i + 2,
                16 * i + 3,
                16 * i + 4,
                16 * i + 5,
                16 * i + 6,
                16 * i + 7,
                16 * i + 8,
                16 * i + 9,
                16 * i + 10,
                16 * i + 11,
                16 * i + 12,
                16 * i + 13,
                16 * i + 14,
                16 * i + 15,
            );
        }

        for i in 0..8 {
            $round(
                $block,
                2 * i,
                2 * i + 1,
                2 * i + 16,
                2 * i + 17,
                2 * i + 32,
                2 * i + 33,
                2 * i + 48,
                2 * i + 49,
                2 * i + 64,
                2 * i + 65,
                2 * i + 80,
                2 * i + 81,
                2 * i + 96,
                2 * i + 97,
                2 * i + 112,
                2 * i + 113,
            );
        }
    }};
}

#[cfg(all(feature = "simd_backend", feature = "nightly"))]
mod argon2_simd;
#[cfg(any(test, not(all(feature = "simd_backend", feature = "nightly"))))]
mod argon2_soft;
#[cfg(target_arch = "x86_64")]
mod argon2_x86_64;

#[cfg(all(feature = "simd_backend", feature = "nightly"))]
use argon2_simd::fill_block as fill_block_portable;
#[cfg(not(all(feature = "simd_backend", feature = "nightly")))]
use argon2_soft::fill_block as fill_block_portable;

/// Overwrites `dst` with the compression of `prev_block` and `ref_block`,
/// `P(R) ^ R` for `R = prev_block ^ ref_block`, XORing the previous contents
/// of `dst` in as well when `xor_old` (the second and later passes). Uses the
/// runtime-detected x86-64 kernel when there is one, else the portable
/// backend.
#[inline]
fn fill_block(
    dst: &mut Block,
    prev_block: &Block,
    ref_block: &Block,
    xor_old: bool,
    scratch: &mut Block,
) {
    #[cfg(target_arch = "x86_64")]
    if let Some(kernel) = argon2_x86_64::detect() {
        kernel.fill_block(dst, prev_block, ref_block, xor_old, scratch);
        return;
    }
    fill_block_portable(dst, prev_block, ref_block, xor_old, scratch);
}

#[derive(Default)]
struct BlockRegion {
    memory: Vec<Block>,
}

struct Argon2Instance {
    region: BlockRegion,
    pseudo_rands: Vec<u64>,
    passes: u32,        /* Number of passes */
    memory_blocks: u32, /* Number of blocks in memory */
    segment_length: u32,
    lane_length: u32,
    lanes: u32,
    type_: Argon2Type,
}

impl Drop for Argon2Instance {
    fn drop(&mut self) {
        self.pseudo_rands.zeroize();
    }
}

impl Default for Argon2Instance {
    fn default() -> Self {
        Self {
            region: Default::default(),
            pseudo_rands: vec![],
            passes: 0,
            memory_blocks: 0,
            segment_length: 0,
            lane_length: 0,
            lanes: 0,
            type_: Argon2Type::Argon2id,
        }
    }
}

impl Argon2Instance {
    fn new(
        memory_blocks: u32,
        segment_length: u32,
        type_: Argon2Type,
        t_cost: u32,
        lanes: u32,
    ) -> Result<Self, Error> {
        let mut ret = Self {
            region: BlockRegion::default(),
            pseudo_rands: Vec::new(),
            memory_blocks,
            segment_length,
            type_,
            lane_length: segment_length * ARGON2_SYNC_POINTS,
            passes: t_cost,
            lanes,
        };
        ret.initialize()?;
        Ok(ret)
    }

    fn initialize(&mut self) -> Result<(), Error> {
        // 1. Memory allocation
        try_reserve_argon2(&mut self.region.memory, self.memory_blocks as usize)?;
        try_reserve_argon2(&mut self.pseudo_rands, self.segment_length as usize)?;
        self.region
            .memory
            .resize(self.memory_blocks as usize, Default::default());
        self.pseudo_rands.resize(self.segment_length as usize, 0);
        Ok(())
    }
}

fn try_reserve_argon2<T>(values: &mut Vec<T>, additional: usize) -> Result<(), Error> {
    values
        .try_reserve_exact(additional)
        .map_err(|_| Error::allocation_failed(crate::ErrorContext::MemoryCost))
}

impl<'a> Argon2Context<'a> {
    #[allow(clippy::too_many_arguments)]
    fn new(
        output: &'a mut [u8],
        password: &'a [u8],
        salt: &'a [u8],
        secret: Option<&'a [u8]>,
        ad: Option<&'a [u8]>,
        t_cost: u32,
        m_cost: u32,
        parallelism: u32,
    ) -> Result<Self, Error> {
        // validate the inputs
        validate_argon2_pwhash_parameters(output.len(), salt.len(), t_cost, m_cost, parallelism)?;
        validate_length!(
            ARGON2_MIN_PWD_LENGTH,
            ARGON2_MAX_PWD_LENGTH,
            password.len(),
            crate::ErrorContext::Password
        );
        if let Some(secret) = secret {
            validate_length!(
                ARGON2_MIN_SECRET,
                ARGON2_MAX_SECRET,
                secret.len(),
                crate::ErrorContext::Secret
            );
        }
        if let Some(ad) = ad {
            validate_length!(
                ARGON2_MIN_AD_LENGTH,
                ARGON2_MAX_AD_LENGTH,
                ad.len(),
                crate::ErrorContext::AssociatedData
            );
        }

        Ok(Self {
            output,
            password,
            salt,
            secret,
            ad,
            t_cost,
            m_cost,
            lanes: parallelism,
        })
    }
}

pub(crate) fn validate_argon2_pwhash_parameters(
    output_len: usize,
    salt_len: usize,
    t_cost: u32,
    m_cost: u32,
    parallelism: u32,
) -> Result<(), Error> {
    validate_length!(
        ARGON2_MIN_OUTLEN,
        ARGON2_MAX_OUTLEN,
        output_len,
        crate::ErrorContext::Output
    );
    validate_length!(
        ARGON2_MIN_SALT_LENGTH,
        ARGON2_MAX_SALT_LENGTH,
        salt_len,
        crate::ErrorContext::PasswordHashSalt
    );
    validate_value!(
        ARGON2_MIN_LANES,
        ARGON2_MAX_LANES,
        parallelism,
        crate::ErrorContext::Parallelism
    );
    let minimum_memory = ARGON2_MIN_MEMORY * parallelism;
    validate_value!(
        minimum_memory,
        ARGON2_MAX_MEMORY,
        m_cost,
        crate::ErrorContext::MemoryCost
    );
    validate_value!(
        ARGON2_MIN_TIME,
        ARGON2_MAX_TIME,
        t_cost,
        crate::ErrorContext::TimeCost
    );
    Ok(())
}

struct Argon2Context<'a> {
    output: &'a mut [u8],
    password: &'a [u8],
    salt: &'a [u8],
    secret: Option<&'a [u8]>,
    ad: Option<&'a [u8]>,
    t_cost: u32, // number of passes
    m_cost: u32, // amount of memory requested (KB)
    lanes: u32,  // number of lanes
}

#[allow(clippy::too_many_arguments)]
pub(crate) fn argon2_hash(
    t_cost: u32,
    m_cost: u32,
    parallelism: u32,
    password: &[u8],
    salt: &[u8],
    secret: Option<&[u8]>,
    ad: Option<&[u8]>,
    output: &mut [u8],
    type_: Argon2Type,
) -> Result<(), Error> {
    let context = Argon2Context::new(
        output,
        password,
        salt,
        secret,
        ad,
        t_cost,
        m_cost,
        parallelism,
    )?;

    let memory_blocks = if m_cost < 2 * ARGON2_SYNC_POINTS * parallelism {
        2 * ARGON2_SYNC_POINTS * parallelism
    } else {
        m_cost
    };

    let segment_length = memory_blocks / (parallelism * ARGON2_SYNC_POINTS);
    /* Ensure that all segments have equal length */
    let memory_blocks = segment_length * (parallelism * ARGON2_SYNC_POINTS);

    let mut instance =
        Argon2Instance::new(memory_blocks, segment_length, type_, t_cost, parallelism)?;

    // 2. Initial hashing
    // H_0 + 8 extra bytes to produce the first blocks
    // Hashing all inputs
    let blockhash = argon2_initial_hash(&context, type_)?;
    // Zeroing 8 extra bytes

    // 3. Creating first blocks, we always have at least two blocks in a
    // slice
    argon2_fill_first_blocks(blockhash, &mut instance)?;

    for pass in 0..instance.passes {
        argon2_fill_memory_blocks(&mut instance, pass);
    }

    argon2_finalize(context, instance)
}

fn argon2_finalize(context: Argon2Context, instance: Argon2Instance) -> Result<(), Error> {
    let mut blockhash = Block::default();
    copy_block(
        &mut blockhash,
        &instance.region.memory[instance.lane_length.wrapping_sub(1) as usize],
    );

    /* XOR the last blocks */
    for l in 1..instance.lanes {
        let last_block_in_lane = (l * instance.lane_length + (instance.lane_length - 1)) as usize;
        xor_block(&mut blockhash, &instance.region.memory[last_block_in_lane]);
    }

    let mut blockhash_bytes = Zeroizing::new([0u8; ARGON2_BLOCK_SIZE]);
    store_block(&mut blockhash_bytes[..], &blockhash);
    blake2b::longhash(context.output, &blockhash_bytes[..])
}

fn argon2_initial_hash(
    context: &Argon2Context,
    type_: Argon2Type,
) -> Result<Zeroizing<[u8; ARGON2_PREHASH_SEED_LENGTH]>, Error> {
    let mut blake2b = blake2b::State::init(ARGON2_PREHASH_DIGEST_LENGTH as u8, None, None, None)?;
    blake2b.update(&context.lanes.to_le_bytes());
    blake2b.update(&(context.output.len() as u32).to_le_bytes());
    blake2b.update(&context.m_cost.to_le_bytes());
    blake2b.update(&context.t_cost.to_le_bytes());
    blake2b.update(&ARGON2_VERSION_NUMBER.to_le_bytes());
    blake2b.update(&(type_ as u32).to_le_bytes());
    blake2b.update(&(context.password.len() as u32).to_le_bytes());
    if !context.password.is_empty() {
        blake2b.update(context.password);
    }
    blake2b.update(&(context.salt.len() as u32).to_le_bytes());
    if !context.salt.is_empty() {
        blake2b.update(context.salt);
    }

    match context.secret {
        Some(secret) => {
            blake2b.update(&(secret.len() as u32).to_le_bytes());
            if !secret.is_empty() {
                blake2b.update(secret);
            }
        }
        None => blake2b.update(&(0u32.to_le_bytes())), // secret, unused
    }
    match context.ad {
        Some(ad) => {
            blake2b.update(&(ad.len() as u32).to_le_bytes());
            if !ad.is_empty() {
                blake2b.update(ad);
            }
        }
        None => blake2b.update(&(0u32.to_le_bytes())), // ad, unused
    }

    let mut blockhash = Zeroizing::new([0u8; ARGON2_PREHASH_SEED_LENGTH]);
    blake2b.finalize(&mut blockhash[..ARGON2_PREHASH_DIGEST_LENGTH])?;
    Ok(blockhash)
}

#[derive(Default)]
struct Argon2Position {
    pass: u32,
    lane: u32,
    slice: u8,
    index: u32,
}

fn argon2_fill_memory_blocks(instance: &mut Argon2Instance, pass: u32) {
    let mut position = Argon2Position {
        pass,
        ..Default::default()
    };
    for s in 0..ARGON2_SYNC_POINTS {
        position.slice = s as u8;
        for l in 0..instance.lanes {
            position.lane = l;
            position.index = 0;
            fill_segment(instance, &mut position);
        }
    }
}

fn fill_segment(instance: &mut Argon2Instance, position: &mut Argon2Position) {
    let data_independent_addressing = !(instance.type_ == Argon2Type::Argon2id
        && (position.pass != 0 || position.slice as u32 >= (ARGON2_SYNC_POINTS / 2)));

    if data_independent_addressing {
        generate_addresses(instance, position);
    }

    let starting_index = if position.pass == 0 && position.slice == 0 {
        2
    } else {
        0
    };

    let curr_offset = position.lane * instance.lane_length
        + position.slice as u32 * instance.segment_length
        + starting_index;

    let mut prev_offset = if curr_offset.is_multiple_of(instance.lane_length) {
        curr_offset + instance.lane_length - 1
    } else {
        curr_offset - 1
    };

    let mut scratch = Block::default();

    for (curr_offset, i) in (curr_offset..).zip(starting_index..instance.segment_length) {
        if curr_offset % instance.lane_length == 1 {
            prev_offset = curr_offset - 1;
        }

        let pseudo_rand = if data_independent_addressing {
            instance.pseudo_rands[i as usize]
        } else {
            instance.region.memory[prev_offset as usize].v[0]
        };

        let ref_lane = if position.pass == 0 && position.slice == 0 {
            position.lane as u64
        } else {
            (pseudo_rand >> 32) % instance.lanes as u64
        };

        position.index = i;
        let ref_index = index_alpha(
            instance,
            position,
            (pseudo_rand & 0xFFFFFFFF) as u32,
            ref_lane == position.lane as u64,
        );

        let ref_offset = (instance.lane_length as u64 * ref_lane + ref_index as u64) as usize;
        // The reference block is never the current or the previous one
        // (`index_alpha` excludes them), and the previous block is a
        // different slot by construction, so the three are disjoint.
        let [curr_block, prev_block, ref_block] = instance
            .region
            .memory
            .get_disjoint_mut([curr_offset as usize, prev_offset as usize, ref_offset])
            .expect("argon2 current, previous and reference blocks are distinct");
        fill_block(
            curr_block,
            prev_block,
            ref_block,
            position.pass != 0,
            &mut scratch,
        );
        prev_offset += 1;
    }
}

fn index_alpha(
    instance: &Argon2Instance,
    position: &Argon2Position,
    pseudo_rand: u32,
    same_lane: bool,
) -> u32 {
    /*
     * Pass 0:
     *      This lane : all already finished segments plus already
     * constructed blocks in this segment
     *      Other lanes : all already finished segments
     * Pass 1+:
     *      This lane : (SYNC_POINTS - 1) last segments plus already
     * constructed blocks in this segment
     *      Other lanes : (SYNC_POINTS - 1) last segments
     */
    let reference_area_size = if position.pass == 0 {
        /* First pass */
        if position.slice == 0 {
            /* First slice */
            position.index - 1 /* all but the previous */
        } else if same_lane {
            /* The same lane => add current segment */
            position.slice as u32 * instance.segment_length + position.index - 1
        } else if position.index == 0 {
            position.slice as u32 * instance.segment_length - 1
        } else {
            position.slice as u32 * instance.segment_length
        }
        /* Second pass */
    } else if same_lane {
        instance.lane_length - instance.segment_length + position.index - 1
    } else if position.index == 0 {
        instance.lane_length - instance.segment_length - 1
    } else {
        instance.lane_length - instance.segment_length
    };

    /* 1.2.4. Mapping pseudo_rand to 0..<reference_area_size-1> and produce
     * relative position */
    let mut relative_position = pseudo_rand;
    relative_position =
        ((relative_position as u64).wrapping_mul(relative_position as u64) >> 32) as u32;
    relative_position = reference_area_size
        - 1
        - ((reference_area_size as u64).wrapping_mul(relative_position as u64) >> 32) as u32;

    /* 1.2.5 Computing starting position */
    let start_position = if position.pass != 0 {
        if position.slice as u32 == ARGON2_SYNC_POINTS - 1 {
            0
        } else {
            (position.slice as u32 + 1) * instance.segment_length
        }
    } else {
        0
    };

    /* 1.2.6. Computing absolute position */
    (start_position + relative_position) % instance.lane_length /* absolute position */
}

fn generate_addresses(instance: &mut Argon2Instance, position: &Argon2Position) {
    let mut input_block = Block::default();
    let zero_block = Block::default();
    let mut tmp_block = Block::default();
    let mut address_block = Block::default();
    let mut scratch = Block::default();

    input_block.v[0] = position.pass as u64;
    input_block.v[1] = position.lane as u64;
    input_block.v[2] = position.slice as u64;
    input_block.v[3] = instance.memory_blocks as u64;
    input_block.v[4] = instance.passes as u64;
    input_block.v[5] = instance.type_ as u64;

    for i in 0..instance.segment_length {
        if i.is_multiple_of(ARGON2_ADDRESSES_IN_BLOCK) {
            input_block.v[6] += 1;
            fill_block(
                &mut tmp_block,
                &zero_block,
                &input_block,
                false,
                &mut scratch,
            );
            fill_block(
                &mut address_block,
                &zero_block,
                &tmp_block,
                false,
                &mut scratch,
            );
        }

        instance.pseudo_rands[i as usize] =
            address_block.v[(i % ARGON2_ADDRESSES_IN_BLOCK) as usize];
    }
}

/// Sets `dst` up as the permutation input `R = prev_block ^ ref_block`. When
/// `xor_old`, `scratch` receives `R ^ old dst`, everything the finished
/// permutation has to be XORed with; otherwise `R` is recomputed from its
/// unchanged inputs by [`finish_in_place`] and `scratch` is untouched.
#[inline]
fn prepare_in_place(
    dst: &mut Block,
    prev_block: &Block,
    ref_block: &Block,
    xor_old: bool,
    scratch: &mut Block,
) {
    if xor_old {
        for i in 0..ARGON2_QWORDS_IN_BLOCK {
            let r = prev_block.v[i] ^ ref_block.v[i];
            scratch.v[i] = dst.v[i] ^ r;
            dst.v[i] = r;
        }
    } else {
        for i in 0..ARGON2_QWORDS_IN_BLOCK {
            dst.v[i] = prev_block.v[i] ^ ref_block.v[i];
        }
    }
}

/// Turns the permuted `dst = P(R)` into the new block `P(R) ^ R [^ old]`,
/// with `scratch` as left by [`prepare_in_place`] for the same `xor_old`.
#[inline]
fn finish_in_place(
    dst: &mut Block,
    prev_block: &Block,
    ref_block: &Block,
    xor_old: bool,
    scratch: &Block,
) {
    if xor_old {
        for i in 0..ARGON2_QWORDS_IN_BLOCK {
            dst.v[i] ^= scratch.v[i];
        }
    } else {
        for i in 0..ARGON2_QWORDS_IN_BLOCK {
            dst.v[i] ^= prev_block.v[i] ^ ref_block.v[i];
        }
    }
}

fn copy_block(dst: &mut Block, src: &Block) {
    dst.v.copy_from_slice(&src.v)
}

/* XOR @src onto @dst bytewise */
fn xor_block(dst: &mut Block, src: &Block) {
    for i in 0..(dst.v.len()) {
        dst.v[i] ^= src.v[i];
    }
}

fn argon2_fill_first_blocks(
    mut blockhash: Zeroizing<[u8; ARGON2_PREHASH_SEED_LENGTH]>,
    instance: &mut Argon2Instance,
) -> Result<(), Error> {
    let mut blockhash_bytes = Zeroizing::new([0u8; ARGON2_BLOCK_SIZE]);

    for l in 0..instance.lanes {
        blockhash[ARGON2_PREHASH_DIGEST_LENGTH..(ARGON2_PREHASH_DIGEST_LENGTH + 4)]
            .copy_from_slice(&[0, 0, 0, 0]);
        blockhash[(ARGON2_PREHASH_DIGEST_LENGTH + 4)..(ARGON2_PREHASH_DIGEST_LENGTH + 8)]
            .copy_from_slice(&l.to_le_bytes());
        blake2b::longhash(&mut blockhash_bytes[..], &blockhash[..])?;

        load_block(
            &mut instance.region.memory[(l * instance.lane_length) as usize],
            &blockhash_bytes[..],
        );

        blockhash[ARGON2_PREHASH_DIGEST_LENGTH..(ARGON2_PREHASH_DIGEST_LENGTH + 4)]
            .copy_from_slice(&[1, 0, 0, 0]);
        blake2b::longhash(&mut blockhash_bytes[..], &blockhash[..])?;
        load_block(
            &mut instance.region.memory[(l * instance.lane_length + 1) as usize],
            &blockhash_bytes[..],
        );
    }

    Ok(())
}

fn load_block(block: &mut Block, input: &[u8]) {
    let (words, _) = input.as_chunks::<8>();
    for (word, bytes) in block.v.iter_mut().zip(words) {
        *word = u64::from_le_bytes(*bytes);
    }
}

fn store_block(output: &mut [u8], block: &Block) {
    let (words, _) = output.as_chunks_mut::<8>();
    for (bytes, word) in words.iter_mut().zip(block.v.iter()) {
        *bytes = word.to_le_bytes();
    }
}

#[cfg(test)]
mod tests {
    #[cfg(feature = "nightly")]
    extern crate test;

    use super::*;

    #[test]
    fn secret_working_types_zeroize_on_drop() {
        assert!(std::mem::needs_drop::<Block>());
        assert!(std::mem::needs_drop::<Argon2Instance>());
    }

    #[test]
    fn impossible_memory_reservation_returns_an_error() {
        let mut blocks = Vec::<Block>::new();
        assert!(matches!(
            try_reserve_argon2(&mut blocks, usize::MAX),
            Err(Error::AllocationFailed {
                context: crate::ErrorContext::MemoryCost,
            })
        ));
    }

    #[test]
    fn context_rejects_invalid_parameters_with_specific_errors() {
        fn context_error(
            output_len: usize,
            salt_len: usize,
            t_cost: u32,
            m_cost: u32,
            parallelism: u32,
        ) -> Error {
            let mut output = vec![0u8; output_len];
            let salt = vec![0u8; salt_len];
            match Argon2Context::new(
                &mut output,
                b"password",
                &salt,
                None,
                None,
                t_cost,
                m_cost,
                parallelism,
            ) {
                Ok(_) => panic!("invalid Argon2 parameters should fail"),
                Err(error) => error,
            }
        }

        let cases = [
            (
                context_error(ARGON2_MIN_OUTLEN - 1, ARGON2_MIN_SALT_LENGTH, 1, 8, 1),
                crate::ErrorContext::Output,
            ),
            (
                context_error(ARGON2_MIN_OUTLEN, ARGON2_MIN_SALT_LENGTH - 1, 1, 8, 1),
                crate::ErrorContext::PasswordHashSalt,
            ),
            (
                context_error(ARGON2_MIN_OUTLEN, ARGON2_MIN_SALT_LENGTH, 1, 8, 0),
                crate::ErrorContext::Parallelism,
            ),
            (
                context_error(
                    ARGON2_MIN_OUTLEN,
                    ARGON2_MIN_SALT_LENGTH,
                    1,
                    ARGON2_MIN_MEMORY - 1,
                    1,
                ),
                crate::ErrorContext::MemoryCost,
            ),
            (
                context_error(ARGON2_MIN_OUTLEN, ARGON2_MIN_SALT_LENGTH, 1, 8, 2),
                crate::ErrorContext::MemoryCost,
            ),
            (
                context_error(ARGON2_MIN_OUTLEN, ARGON2_MIN_SALT_LENGTH, 0, 8, 1),
                crate::ErrorContext::TimeCost,
            ),
        ];

        for (error, expected_context) in cases {
            let context = match error {
                Error::InvalidLength { context, .. } | Error::InvalidValue { context, .. } => {
                    context
                }
                other => panic!("unexpected Argon2 error: {other:?}"),
            };
            assert_eq!(context, expected_context);
        }

        let salt = [0u8; ARGON2_MIN_SALT_LENGTH];
        for parallelism in [0, u32::MAX] {
            let mut output = [0u8; ARGON2_MIN_OUTLEN];
            assert!(
                argon2_hash(
                    1,
                    8,
                    parallelism,
                    b"password",
                    &salt,
                    None,
                    None,
                    &mut output,
                    Argon2Type::Argon2id,
                )
                .is_err()
            );
        }
    }

    /// Direct upper bounds are rejected before allocation or hashing. `t_cost`
    /// and `m_cost` are already `u32`; their representable maxima are valid,
    /// so only wider lengths and the 24-bit lane bound have a value above max.
    #[test]
    fn validator_rejects_representable_upper_bound_overflows() {
        if let Some(output_len) = ARGON2_MAX_OUTLEN.checked_add(1) {
            assert!(matches!(
                validate_argon2_pwhash_parameters(output_len, ARGON2_MIN_SALT_LENGTH, 1, 8, 1,),
                Err(Error::InvalidLength {
                    context: crate::ErrorContext::Output,
                    ..
                })
            ));
        }
        if let Some(salt_len) = ARGON2_MAX_SALT_LENGTH.checked_add(1) {
            assert!(matches!(
                validate_argon2_pwhash_parameters(ARGON2_MIN_OUTLEN, salt_len, 1, 8, 1,),
                Err(Error::InvalidLength {
                    context: crate::ErrorContext::PasswordHashSalt,
                    ..
                })
            ));
        }
        assert!(matches!(
            validate_argon2_pwhash_parameters(
                ARGON2_MIN_OUTLEN,
                ARGON2_MIN_SALT_LENGTH,
                1,
                8 * (ARGON2_MAX_LANES + 1),
                ARGON2_MAX_LANES + 1,
            ),
            Err(Error::InvalidValue {
                context: crate::ErrorContext::Parallelism,
                ..
            })
        ));
        // `ARGON2_MAX_MEMORY` is `u32::MAX` on 64-bit targets, so an
        // over-maximum value only exists on 32-bit ones.
        if let Some(m_cost) = ARGON2_MAX_MEMORY.checked_add(1) {
            assert!(matches!(
                validate_argon2_pwhash_parameters(
                    ARGON2_MIN_OUTLEN,
                    ARGON2_MIN_SALT_LENGTH,
                    1,
                    m_cost,
                    1,
                ),
                Err(Error::InvalidValue {
                    context: crate::ErrorContext::MemoryCost,
                    ..
                })
            ));
        }
    }

    #[cfg(feature = "nightly")]
    fn bench_argon2id(b: &mut test::Bencher, t_cost: u32, m_cost: u32) {
        let password = [1u8; 32];
        let salt = [2u8; 16];
        let mut hash = [0u8; 32];

        b.bytes = t_cost as u64 * m_cost as u64 * 1024;
        b.iter(|| {
            super::argon2_hash(
                test::black_box(t_cost),
                test::black_box(m_cost),
                1,
                test::black_box(&password),
                test::black_box(&salt),
                None,
                None,
                test::black_box(&mut hash),
                Argon2Type::Argon2id,
            )
            .expect("argon2_hash failed");
            test::black_box(&hash);
        });
    }

    #[cfg(any(
        all(feature = "simd_backend", feature = "nightly"),
        target_arch = "x86_64"
    ))]
    fn test_block(seed: u64) -> Block {
        let mut block = Block::default();
        for (i, word) in block.v.iter_mut().enumerate() {
            let i = i as u64;
            *word = seed
                .wrapping_add(i.wrapping_mul(0x9e37_79b9_7f4a_7c15))
                .rotate_left((i % 64) as u32);
        }
        block
    }

    /// Zero blocks, structured blocks and random blocks, both overwriting
    /// the destination (first pass, `None`) and XORing into it (later
    /// passes, `Some(old)`).
    #[cfg(any(
        all(feature = "simd_backend", feature = "nightly"),
        target_arch = "x86_64"
    ))]
    fn fill_block_cases() -> Vec<(Block, Block, Option<Block>)> {
        let mut cases = vec![
            (Block::default(), Block::default(), None),
            (test_block(0), test_block(1), None),
            (
                test_block(0x0123_4567_89ab_cdef),
                test_block(0xfedc_ba98_7654_3210),
                None,
            ),
            (
                test_block(0x1111_2222_3333_4444),
                test_block(0x5555_6666_7777_8888),
                Some(test_block(0x9999_aaaa_bbbb_cccc)),
            ),
        ];
        let mut s = 0x9e37_79b9_7f4a_7c15u64;
        let mut random_block = || {
            let mut block = Block::default();
            for word in block.v.iter_mut() {
                s ^= s << 13;
                s ^= s >> 7;
                s ^= s << 17;
                *word = s;
            }
            block
        };
        for i in 0..256 {
            let xor_old = (i % 2 == 1).then(&mut random_block);
            cases.push((random_block(), random_block(), xor_old));
        }
        cases
    }

    /// Every case of [`fill_block_cases`] through `candidate` must match the
    /// scalar block compression.
    #[cfg(any(
        all(feature = "simd_backend", feature = "nightly"),
        target_arch = "x86_64"
    ))]
    fn check_fill_block_matches_soft(
        name: &str,
        mut candidate: impl FnMut(&mut Block, &Block, &Block, bool, &mut Block),
    ) {
        for (i, (prev_block, ref_block, next_block)) in fill_block_cases().into_iter().enumerate() {
            let mut soft = next_block.clone().unwrap_or_default();
            let mut soft_scratch = Block::default();
            argon2_soft::fill_block(
                &mut soft,
                &prev_block,
                &ref_block,
                next_block.is_some(),
                &mut soft_scratch,
            );
            let mut actual = next_block.clone().unwrap_or_default();
            let mut scratch = Block::default();
            candidate(
                &mut actual,
                &prev_block,
                &ref_block,
                next_block.is_some(),
                &mut scratch,
            );
            assert_eq!(soft.v, actual.v, "{name} case {i}");
        }
    }

    /// The portable-SIMD block compression matches the scalar one.
    #[cfg(all(feature = "simd_backend", feature = "nightly"))]
    #[test]
    fn test_fill_block_simd_matches_soft() {
        check_fill_block_matches_soft("portable simd", argon2_simd::fill_block);
    }

    /// Every x86-64 kernel the CPU supports matches the scalar block
    /// compression, and the production dispatch agrees with the scalar one.
    #[cfg(target_arch = "x86_64")]
    #[test]
    fn test_fill_block_x86_64_matches_soft() {
        for kernel in argon2_x86_64::Kernel::all() {
            check_fill_block_matches_soft(&format!("{kernel:?}"), |d, p, r, x, s| {
                kernel.fill_block(d, p, r, x, s)
            });
        }
        check_fill_block_matches_soft("dispatch", fill_block);
    }

    #[test]
    fn test_vector_argon2i() {
        let password = [1u8; 32];
        let salt = [2u8; 16];
        let secret = [3u8; 8];
        let ad = [4u8; 12];

        let mut hash = [0u8; 32];

        super::argon2_hash(
            3,
            32,
            4,
            &password,
            &salt,
            Some(&secret),
            Some(&ad),
            &mut hash,
            Argon2Type::Argon2i,
        )
        .expect("argon2_hash failed");

        assert_eq!(
            hash,
            [
                0xc8, 0x14, 0xd9, 0xd1, 0xdc, 0x7f, 0x37, 0xaa, 0x13, 0xf0, 0xd7, 0x7f, 0x24, 0x94,
                0xbd, 0xa1, 0xc8, 0xde, 0x6b, 0x01, 0x6d, 0xd3, 0x88, 0xd2, 0x99, 0x52, 0xa4, 0xc4,
                0x67, 0x2b, 0x6c, 0xe8,
            ]
        );
    }

    #[test]
    fn test_vector_argon2id() {
        let password = [1u8; 32];
        let salt = [2u8; 16];
        let secret = [3u8; 8];
        let ad = [4u8; 12];

        let mut hash = [0u8; 32];

        super::argon2_hash(
            3,
            32,
            4,
            &password,
            &salt,
            Some(&secret),
            Some(&ad),
            &mut hash,
            Argon2Type::Argon2id,
        )
        .expect("argon2_hash failed");

        assert_eq!(
            hash,
            [
                0x0d, 0x64, 0x0d, 0xf5, 0x8d, 0x78, 0x76, 0x6c, 0x08, 0xc0, 0x37, 0xa3, 0x4a, 0x8b,
                0x53, 0xc9, 0xd0, 0x1e, 0xf0, 0x45, 0x2d, 0x75, 0xb6, 0x5e, 0xb5, 0x25, 0x20, 0xe9,
                0x6b, 0x01, 0xe6, 0x59,
            ]
        );
    }

    #[cfg(feature = "nightly")]
    #[bench]
    fn argon2id_64kib_bench(b: &mut test::Bencher) {
        bench_argon2id(b, 2, 64);
    }

    #[cfg(feature = "nightly")]
    #[bench]
    fn argon2id_1mib_bench(b: &mut test::Bencher) {
        bench_argon2id(b, 2, 1024);
    }

    #[cfg(dryoc_native_tests)]
    mod native_tests {
        use super::*;

        unsafe extern "C" {
            fn argon2_hash(
                t_cost: u32,
                m_cost: u32,
                parallelism: u32,
                pwd: *const u8,
                pwdlen: usize,
                salt: *const u8,
                saltlen: usize,
                hash: *mut u8,
                hashlen: usize,
                encoded: *mut u8,
                encodedlen: usize,
                type_: i32,
            ) -> i32;
        }

        #[test]
        fn test_vector_argon2id_so() {
            let password = [1u8; 32];
            let salt = [2u8; 16];

            let mut hash = [0u8; 32];
            let mut so_hash = [0u8; 32];

            super::argon2_hash(
                3,
                32,
                4,
                &password,
                &salt,
                None,
                None,
                &mut hash,
                Argon2Type::Argon2id,
            )
            .expect("argon2_hash failed");

            unsafe {
                argon2_hash(
                    3,
                    32,
                    4,
                    password.as_ptr(),
                    password.len(),
                    salt.as_ptr(),
                    salt.len(),
                    so_hash.as_mut_ptr(),
                    so_hash.len(),
                    std::ptr::null_mut(),
                    0,
                    Argon2Type::Argon2id as i32,
                );
            }

            assert_eq!(hash, so_hash);

            assert_eq!(
                hash,
                [
                    3, 170, 185, 101, 193, 32, 1, 201, 215, 208, 210, 222, 51, 25, 44, 4, 148, 182,
                    132, 187, 20, 129, 150, 215, 60, 29, 241, 172, 175, 109, 12, 46
                ]
            );
        }

        /// Additional low-cost cases around the minimum-memory lane rule,
        /// including the p=1,t=1 path and p=4 lane initialization, for both
        /// RFC 9106 variants. This uses libargon2 directly because libsodium's
        /// high-level Argon2i API imposes a larger minimum operation count.
        #[test]
        fn test_low_cost_parameter_matrix_matches_libargon2() {
            let password = b"deterministic password";
            let salt = b"saltsalt";
            for type_ in [Argon2Type::Argon2i, Argon2Type::Argon2id] {
                for (t_cost, m_cost, parallelism) in [(1, 8, 1), (1, 9, 1), (1, 32, 4), (2, 64, 4)]
                {
                    let mut ours = [0u8; 32];
                    let mut native = [0u8; 32];
                    super::argon2_hash(
                        t_cost,
                        m_cost,
                        parallelism,
                        password,
                        salt,
                        None,
                        None,
                        &mut ours,
                        type_,
                    )
                    .expect("dryoc argon2");
                    let rc = unsafe {
                        argon2_hash(
                            t_cost,
                            m_cost,
                            parallelism,
                            password.as_ptr(),
                            password.len(),
                            salt.as_ptr(),
                            salt.len(),
                            native.as_mut_ptr(),
                            native.len(),
                            std::ptr::null_mut(),
                            0,
                            type_ as i32,
                        )
                    };
                    assert_eq!(rc, 0);
                    assert_eq!(
                        ours, native,
                        "type {}, t {t_cost}, m {m_cost}, p {parallelism}",
                        type_ as i32
                    );
                }
            }
        }

        /// libsodium's `argon2_hash` with the same parameters as
        /// `bench_argon2id`, so the two rows are directly comparable.
        #[cfg(feature = "nightly")]
        fn bench_libsodium_argon2id(b: &mut test::Bencher, t_cost: u32, m_cost: u32) {
            sodiumoxide::init().expect("sodiumoxide init");

            let password = [1u8; 32];
            let salt = [2u8; 16];
            let mut hash = [0u8; 32];

            b.bytes = t_cost as u64 * m_cost as u64 * 1024;
            b.iter(|| {
                // SAFETY: `password`, `salt` and `hash` are valid for the
                // lengths passed; the encoded output is null with zero length.
                let rc = unsafe {
                    argon2_hash(
                        test::black_box(t_cost),
                        test::black_box(m_cost),
                        1,
                        password.as_ptr(),
                        password.len(),
                        salt.as_ptr(),
                        salt.len(),
                        hash.as_mut_ptr(),
                        hash.len(),
                        std::ptr::null_mut(),
                        0,
                        Argon2Type::Argon2id as i32,
                    )
                };
                assert_eq!(rc, 0);
                test::black_box(&hash);
            });
        }

        #[cfg(feature = "nightly")]
        #[bench]
        fn libsodium_argon2id_64kib_bench(b: &mut test::Bencher) {
            bench_libsodium_argon2id(b, 2, 64);
        }

        #[cfg(feature = "nightly")]
        #[bench]
        fn libsodium_argon2id_1mib_bench(b: &mut test::Bencher) {
            bench_libsodium_argon2id(b, 2, 1024);
        }
    }
}
