name: Publish to crates.io

on:
  push:
    tags:
      - v*
env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  discussions: write

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: brndnmtthws/rust-action@v1
        with:
          toolchain: stable
      - run: cargo build
      - run: cargo test
      - name: Authenticate with crates.io
        id: auth
        uses: rust-lang/crates-io-auth-action@v1
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: false
          discussion_category_name: General
          generate_release_notes: true
